version: "3.3"

services:
        db:
                image: postgres:latest
                volumes:
                        - ./data/db:/var/lib/postgresql/data
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
        web:
                build: .
                command: bash -c "wait-for-it -t 30 db:5432 && 
                        python manage.py makemigrations && 
                        python manage.py migrate &&
                        python manage.py runserver 0.0.0.0:8000"
                stdin_open: true
                tty: true
                volumes:
                        - .:/code
                ports:
                        - "8000:8000"
                depends_on:
                        - db
